### PR TITLE
added support for sequential model

### PR DESCRIPTION
**Pull request by hasnainv**

### CODE REVIEW

**Comment by MarcBS** [comment]
@hasnainv , thank you for your contribution.

Although, why do you think it is necessary to allow the conversion module to use a Sequential model? As long as I understand any model could be represented as a Graph model.

Regards.

**Comment by hasnainv** [comment]
It's true that a sequential model is just a special case of a graph. I added this because keras maintains a distinction between sequential and graph models and some people might want to use the sequential model class.

**Comment by MarcBS** [comment]
Yes, I agree that some people might prefer using a Sequential model whenever it is possible. Although, considering that some models can only be converted into a Graph then it would probably be better to just select 'Graph' by default but keep the 'Sequential' as an option as you said.

If you can apply this minor change and solve the fails produced in the checks I will merge your PR.

**Comment by bhack** [comment]
Actually keras has a new [functional api](http://keras.io/getting-started/functional-api-guide/)

**Comment by MarcBS** [comment]
Considering the converter is updated for using the new Functional API models this PR can be closed.

**Pull request closed without merging**
